### ISSUE TITLE
大佬能提供一个html调用流式接口的样例吗？

### ISSUE THREAD

**Issue by SnowyLchen** [weaigc/gpt-web#1]
命令行正常，html直接访问流式接口，就返回几个字母，看似underfind，剩余没返回。
![image](https://github.com/weaigc/gpt-web/assets/52272752/cd772ac0-3648-4a86-917a-912132fd7f93)

**Comment by weaigc** [comment]
@SnowyLchen 修了一个bug, 使用 npm i -g gpt-web@latest 更新到 0.0.5 版本

**Comment by weaigc** [comment]
@SnowyLchen 前端调用的样例
```
const response = await fetch('http://localhost:8000/api/conversation?text=hello')
const decoder = new TextDecoder()

const reader = response.body.getReader();
while (true) {
    const { done, value } = await reader.read();
    if (done) {
      break;
    }
    const text = decoder.decode(value);
    console.log(text)
}
```
更多资料可以参考: https://developer.mozilla.org/en-US/docs/Web/API/Streams_API/Using_readable_streams
