### ISSUE TITLE
反代地址问题

### ISSUE THREAD

**Issue by SnowyLchen** [weaigc/gpt-web#3]
https://ai.fakeopen.com/api/conversation
这个反向代理的配置是如何实现的？可以使用自己的服务器进行代理吗？

**Comment by weaigc** [comment]
> https://ai.fakeopen.com/api/conversation 这个反向代理的配置是如何实现的？可以使用自己的服务器进行代理吗？

不行，这个代理可以绕过cf

**Comment by SnowyLchen** [comment]
> > https://ai.fakeopen.com/api/conversation 这个反向代理的配置是如何实现的？可以使用自己的服务器进行代理吗？
> 
> 不行，这个代理可以绕过cf

那这个代理的原理是什么，我想要支持多人同时问答，这个代理这块就实现不了，只能等待一个回答完成，才可以进行第二个回答

**Comment by weaigc** [comment]
> > > https://ai.fakeopen.com/api/conversation 这个反向代理的配置是如何实现的？可以使用自己的服务器进行代理吗？
> > 
> > 
> > 不行，这个代理可以绕过cf
> 
> 那这个代理的原理是什么，我想要支持多人同时问答，这个代理这块就实现不了，只能等待一个回答完成，才可以进行第二个回答
@SnowyLchen 
这个本身就不支持多人同时回答，如果你需要的话，可以看一下这个项目 https://github.com/weaigc/gradio-chatbot

**Comment by SnowyLchen** [comment]
好的，谢谢

> > > > https://ai.fakeopen.com/api/conversation 这个反向代理的配置是如何实现的？可以使用自己的服务器进行代理吗？
> > > 
> > > 
> > > 不行，这个代理可以绕过cf
> > 
> > 
> > 那这个代理的原理是什么，我想要支持多人同时问答，这个代理这块就实现不了，只能等待一个回答完成，才可以进行第二个回答
> > @SnowyLchen
> > 这个本身就不支持多人同时回答，如果你需要的话，可以看一下这个项目 https://github.com/weaigc/gradio-chatbot

好的，谢谢
