### ISSUE TITLE
[建议] 添加虚假的apikey

### ISSUE THREAD

**Issue by Weoworks** [weaigc/gpt-web#5]
拜托添加一个类似于openai官方的调用方式，谢谢!

**Comment by weaigc** [comment]
> 拜托添加一个类似于openai官方的调用方式，谢谢!

支持的，~~不过现在依赖的 pandora 不能正常使用 https://status.fakeopen.com/~~ 。

**Comment by Weoworks** [comment]
> > 拜托添加一个类似于openai官方的调用方式，谢谢!
> 
> 支持的，不过现在依赖的 pandora 不能正常使用 https://status.fakeopen.com/

可是我并不能在类似chatgpt-next-web中使用！！！
http://154.16.27.172:8000/api/conversation
请帮帮我！

**Comment by weaigc** [comment]
> > > 拜托添加一个类似于openai官方的调用方式，谢谢!
> > 
> > 
> > 支持的，不过现在依赖的 pandora 不能正常使用 https://status.fakeopen.com/
> 
> 可是我并不能在类似chatgpt-next-web中使用！！！ http://154.16.27.172:8000/api/conversation 请帮帮我！
@Weoworks 
安装最新版本 npm i -g gpt-web@0.0.14

**Comment by Weoworks** [comment]
> > > > 拜托添加一个类似于openai官方的调用方式，谢谢!
> > > 
> > > 
> > > 支持的，不过现在依赖的 pandora 不能正常使用 https://status.fakeopen.com/
> > 
> > 
> > 可是我并不能在类似chatgpt-next-web中使用！！！ http://154.16.27.172:8000/api/conversation 请帮帮我！
> > @Weoworks
> > 安装最新版本 npm i -g gpt-web@0.0.14

感谢大佬！！！🥰
